version: '3.9'
services:
  ########################
  # APP SERVICE
  ########################
  app:
    restart: on-failure
    build: .
    healthcheck:
      test: 'env | grep HOME'
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 15s
    ports:
      - '3000:3000'
    volumes:
      - /home/express
      - /home/express/node_modules
    networks:
      - node_network
### ===================================
### NETWORKS GROUP FOR ALL SAME SERVICE
### ===================================
networks:
  node_network:
